### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by phodal** [phodal/vmap#11]
![vmap-arch 1](https://cloud.githubusercontent.com/assets/472311/14230296/52802c38-f983-11e5-9ed1-23deb4230b41.png)
- [ ] Data Crawl:  Collection Information from Zhihu & GitHub & Linkedin (ex. Address) #13
- [ ] Generator:  Generator STATIC HTML from User Details API
- [ ] New Search Homepage
  - [ ] Polygon Search
  - [ ]  Hot City List 
  - [ ]  Map Search 
  - [ ] Input Search 
- [ ] Search Engine 
  - [ ] Define Schema
  - [ ] Data Mining
  - [ ] Data Feeder
